In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('winequality-red.csv')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [5]:
x = df.drop('quality',axis=1)
y = df['quality']

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
lm = LinearRegression()

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [9]:
lm.fit(x_train,y_train)

LinearRegression()

In [10]:
predictions = lm.predict(x_test)

In [11]:
x_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1109,10.8,0.470,0.43,2.10,0.171,27.0,66.0,0.99820,3.17,0.76,10.8
1032,8.1,0.820,0.00,4.10,0.095,5.0,14.0,0.99854,3.36,0.53,9.6
1002,9.1,0.290,0.33,2.05,0.063,13.0,27.0,0.99516,3.26,0.84,11.7
487,10.2,0.645,0.36,1.80,0.053,5.0,14.0,0.99820,3.17,0.42,10.0
979,12.2,0.450,0.49,1.40,0.075,3.0,6.0,0.99690,3.13,0.63,10.4
...,...,...,...,...,...,...,...,...,...,...,...
801,8.6,0.550,0.09,3.30,0.068,8.0,17.0,0.99735,3.23,0.44,10.0
61,7.7,0.690,0.49,1.80,0.115,20.0,112.0,0.99680,3.21,0.71,9.3
431,7.8,0.550,0.35,2.20,0.074,21.0,66.0,0.99740,3.25,0.56,9.2
1210,6.8,0.650,0.02,2.10,0.078,8.0,15.0,0.99498,3.35,0.62,10.4
713,8.0,0.430,0.36,2.30,0.075,10.0,48.0,0.99760,3.34,0.46,9.4

In [12]:
y_test

1109    6
1032    5
1002    7
487     6
979     5
       ..
801     5
61      5
431     5
1210    6
713     5
Name: quality, Length: 480, dtype: int64

In [13]:
check = pd.DataFrame(x_test, columns = ["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "free sulfur dioxide", "total sulfur dioxide", "density", "sulphates", "alcohol"])

In [14]:
check["actual Quality"] = y_test

In [15]:
check["predicted Quality"] = predictions

In [16]:
check

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,sulphates,alcohol,actual Quality,predicted Quality
1109,10.8,0.470,0.43,2.10,0.171,27.0,66.0,0.99820,0.76,10.8,6,5.776983
1032,8.1,0.820,0.00,4.10,0.095,5.0,14.0,0.99854,0.53,9.6,5,5.041862
1002,9.1,0.290,0.33,2.05,0.063,13.0,27.0,0.99516,0.84,11.7,7,6.588130
487,10.2,0.645,0.36,1.80,0.053,5.0,14.0,0.99820,0.42,10.0,6,5.384497
979,12.2,0.450,0.49,1.40,0.075,3.0,6.0,0.99690,0.63,10.4,5,5.942356
...,...,...,...,...,...,...,...,...,...,...,...,...
801,8.6,0.550,0.09,3.30,0.068,8.0,17.0,0.99735,0.44,10.0,5,5.503117
61,7.7,0.690,0.49,1.80,0.115,20.0,112.0,0.99680,0.71,9.3,5,4.952331
431,7.8,0.550,0.35,2.20,0.074,21.0,66.0,0.99740,0.56,9.2,5,5.184073
1210,6.8,0.650,0.02,2.10,0.078,8.0,15.0,0.99498,0.62,10.4,6,5.565374
713,8.0,0.430,0.36,2.30,0.075,10.0,48.0,0.99760,0.46,9.4,5,5.294188